project:
  type: website

website:
  title: "What Makes Restaurants Thrive? How Success Factors Evolved from 2018-2023"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: sources.qmd
    
      - href: model.qmd
      

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true